language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gfortran-4.9
            - cmake
      env:
         - CC=gcc-4.9
         - CXX=g++-4.9
         - FC=gfortran-4.9

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gfortran-5
            - cmake
      env:
         - CC=gcc-5
         - CXX=g++-5
         - FC=gfortran-5

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gfortran-6
            - cmake
      env:
        - CC=gcc-6
        - CXX=g++-6
        - FC=gfortran-6

    # works on Precise and Trusty

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran-7
            - cmake
      env:
        - CC=gcc-7
        - CXX=g++-7
        - FC=gfortran-7

before_install:
    - printenv  # just for debug info that could be helpful

script:
  - mkdir build && cd build
  - cmake ../
  - make
