language: c

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-4.9
            - cmake
      env:
        - FC=gfortran-4.9
        - COV=

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-5
            - cmake
      env:
        - FC=gfortran-5
        - COV=

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-6
            - cmake
      env:
        - FC=gfortran-6
        - COV=--coverage

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-7
            - cmake
      env:
        - FC=gfortran-7
        - COV=

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          packages:
            - cmake
      env:
        - FC=pgf90
        - COV=

before_install:
    - printenv  # just for debug info that could be helpful
    - ./.travis.sh

script:
  - mkdir build && cd build
  - cmake -DCMAKE_Fortran_FLAGS=COV ../
  - make
  - ctest

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: m29ZdRgnXPV+hH+BO62DavSHbTb8UDSIPOOEJ4dOJ2G7JZmO/2+JiWI3Q75lnjmcIHHEYva8b6UmqaXo9zV9sN9FqlVPERl2wD0kIGWQUFYd7kEckcNq5KAQ2WBrmUvQlvo8n039vZELgIwN/xasxWvWZs3aE7upkJe/3HkTU1LRzkF+2xjpXtFEZHioRKPuiDiStlCd9OdGDJI7huSVgl0ZqhdgPhRPstQOWn41dGWCx6AcomAuBFfHK9Q85ytpBd/2XT0wYkRFlJmBXR7eDXXMJsIL2TxWMDNhFYvAKs7gHE/Y3mqwVn0llPuLtu1CJlhGaqCBvcHH0F7yvNd/p50++ljElIs4w69XWqDrQSd3NqAn6NXA4NcDFHToqgYl4ln09/8KcTtLl97+/Of/bUAj7KDud9tuhbncJWqCilXuQqEwstFGcac03vy8WwnljFvarT621cJTRUQKb910TIlw8mv+8nfvKgSFTaZE5JEF/75Ed2GceclWcl2HDblJpNskRWuTGm8/i4ZJqQ7JHDMGpFdRnRoBdBuAD+r74EtKg91ucmSsDO3ouSOGfEyX/Zvp6oUm4ciHVGgRmDTMfT8aYgtq8d2HEFmewML94ByzxegLPxFuLG5Hv8IxIW3pvnF9yHvLWZXSzonSv5GVPkpy8MurlWpsUK9r7ipUDX8=
  email: false


